/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Follow } from "./Follow";
import { FollowCountArgs } from "./FollowCountArgs";
import { FollowFindManyArgs } from "./FollowFindManyArgs";
import { FollowFindUniqueArgs } from "./FollowFindUniqueArgs";
import { DeleteFollowArgs } from "./DeleteFollowArgs";
import { FollowService } from "../follow.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Follow)
export class FollowResolverBase {
  constructor(
    protected readonly service: FollowService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Follow",
    action: "read",
    possession: "any",
  })
  async _followsMeta(
    @graphql.Args() args: FollowCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Follow])
  @nestAccessControl.UseRoles({
    resource: "Follow",
    action: "read",
    possession: "any",
  })
  async follows(@graphql.Args() args: FollowFindManyArgs): Promise<Follow[]> {
    return this.service.follows(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Follow, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Follow",
    action: "read",
    possession: "own",
  })
  async follow(
    @graphql.Args() args: FollowFindUniqueArgs
  ): Promise<Follow | null> {
    const result = await this.service.follow(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Follow)
  @nestAccessControl.UseRoles({
    resource: "Follow",
    action: "delete",
    possession: "any",
  })
  async deleteFollow(
    @graphql.Args() args: DeleteFollowArgs
  ): Promise<Follow | null> {
    try {
      return await this.service.deleteFollow(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
